paicoding:
  mq:
    provider: rocketmq
    rocketmq:
      topic: paicoding-business-event
      comment-consumer-group: paicoding-comment-write-pre-group
      notify-consumer-group: paicoding-notify-pre-group

rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:127.0.0.1:9876}
  producer:
    group: paicoding-producer-pre-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 2
