apiVersion: 1

policies:
  - orgId: 1
    receiver: dynamic-tp-default
    group_by:
      - grafana_folder
      - alertname
    routes:
      - receiver: dynamic-tp-default
        object_matchers:
          - ["pool", "=", "orderThreadPool"]